language: objective-c
osx_image: xcode8
podfile: Example/Podfile
notifications:
  email: false
before_install: 
- gem uninstall cocoapods -a
- gem install cocoapods --pre
- gem install xcpretty
- gem install bundler
- bundle install
- bundle exec pod update --project-directory=Example/

script:
- xcodebuild test -workspace Example/Moya-SwiftyJSONMapper.xcworkspace -scheme Moya-SwiftyJSONMapper-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty -c && exit ${PIPESTATUS[0]}
